### PR TITLE
Fix #23

### LINKED ISSUE #23: fmt.Errorf format %v reads arg #2, but call has 1 arg
[This line](https://github.com/cdipaolo/goml/blob/e1f51f7135988cf33ef5feafa6d1558e4f28d981/cluster/kmeans.go#L521) in kmeans throws an error `fmt.Errorf format %v reads arg #2, but call has 1 arg` while running tests.

A simple fix would be to replace the line in question
```
errors <- fmt.Errorf("ERROR: point.X must have the same dimensions as clusters (len %v). Point: %v", point)
```
with this
```
errors <- fmt.Errorf("ERROR: point.X must have the same dimensions as clusters (len %v). Point: %v", centroids, point)
```

Follow up question, is this project in active development?

### PR DESCRIPTION
**Pull request by ashnair1**
Fix #23

### CODE REVIEW

**Comment by ashnair1** [comment]
Pinging @piazzamp

File: cluster/kmeans.go [hunk 1]
```diff
@@ -518,7 +518,7 @@ func (k *KMeans) OnlineLearn(errors chan error, dataset chan base.Datapoint, onU
 
 		if more {
 			if len(point.X) != features {
-				errors <- fmt.Errorf("ERROR: point.X must have the same dimensions as clusters (len %v). Point: %v", point)
+				errors <- fmt.Errorf("ERROR: point.X must have the same dimensions as clusters (len %v). Point: %v", centroids, point)
```
Comment (piazzamp) [inline cluster/kmeans.go:521]: huh, centroids is len(k.centroids) above so it's already an int 👍

**Review by piazzamp — APPROVED** [review]
